language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - export LIBCURL_NO_PKG_CONFIG=1
  - export RUST_TEST_THREADS=1
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
  - cargo doc --no-deps
  - cargo doc --no-deps -p curl-sys
after_success:
  - travis-cargo --only nightly doc-upload
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
