[package]

name = "curl"
version = "0.2.18"
authors = ["Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT"
repository = "https://github.com/carllerche/curl-rust"
description = "Rust bindings to libcurl for making HTTP requests"

[dependencies]
url = "0.5.0"
libc = "0.2"
curl-sys = { path = "curl-sys", version = "0.1.0" }

[dev-dependencies]
env_logger = "0.3.0"

# Unix platforms use OpenSSL for now to provide SSL functionality
[target."cfg(all(unix, not(target_os = \"macos\")))".dependencies]
openssl-sys = "0.7.0"
[target.i686-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"

[[test]]

name = "test"
path = "test/test.rs"
