[package]
name = "curl-sys"
version = "0.3.16"
authors = ["Carl Lerche <me@carllerche.com>",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT"
repository = "https://github.com/alexcrichton/curl-rust"
description = "Native bindings to the libcurl library"
documentation = "https://docs.rs/curl-sys"
categories = ["external-ffi-bindings"]

[badges]
travis-ci = { repository = "alexcrichton/curl-rust" }
appveyor = { repository = "alexcrichton/curl-rust" }

[lib]
name = "curl_sys"
path = "lib.rs"

[dependencies]
curl-sys = "0.4"
libc = "0.2"

[target.'cfg(windows)'.dependencies]
winapi = "0.2"
