[package]
name = "curl-sys"
version = "0.1.0"
authors = []
links = "curl"
build = "build.rs"

[build-dependencies.pkg-config]
git = "https://github.com/alexcrichton/pkg-config-rs"

[lib]
name = "curl-sys"
path = "lib.rs"

[dependencies.libz-sys]
git = "https://github.com/alexcrichton/libz-sys"

# Unix platforms use OpenSSL for now to provide SSL functionality
[target.i686-apple-darwin.dependencies.openssl-sys]
  git = "https://github.com/sfackler/rust-openssl"
[target.x86_64-apple-darwin.dependencies.openssl-sys]
  git = "https://github.com/sfackler/rust-openssl"
[target.i686-unknown-linux-gnu.dependencies.openssl-sys]
  git = "https://github.com/sfackler/rust-openssl"
[target.x86_64-unknown-linux-gnu.dependencies.openssl-sys]
  git = "https://github.com/sfackler/rust-openssl"
[target.i686-unknown-freebsd.dependencies.openssl-sys]
  git = "https://github.com/sfackler/rust-openssl"
[target.x86_64-unknown-freebsd.dependencies.openssl-sys]
  git = "https://github.com/sfackler/rust-openssl"
